workflows:
  android-workflow:
    name: Build APK
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      java: 17
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android-app/local.properties"
      - name: Build Android APK
        script: |
          cd android-app
          gradle wrapper
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - android-app/app/build/outputs/**/*.apk
